name: .NET CI/CD with Veracode Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build with publish
      run: |
        # Buscar el primer archivo .csproj
        csproj_file=$(find . -name "*.csproj" -print -quit)
        if [ -z "$csproj_file" ]; then
          echo "::error::No .csproj file found"
          exit 1
        fi
        
        # Publicar la aplicación
        dotnet publish "$csproj_file" -c Release -o ./veracode-upload --no-self-contained
        
        # Verificar los archivos generados
        echo "Generated files:"
        ls -R ./veracode-upload

    - name: Clean previous incomplete scans
      run: |
        # Instalar dependencias para la API de Veracode
        sudo apt-get update && sudo apt-get install -y curl jq
        
        # Eliminar escaneos incompletos
        response=$(curl -s -X GET \
          -u "${{ secrets.VERACODE_API_ID }}:${{ secrets.VERACODE_API_KEY }}" \
          "https://analysiscenter.veracode.com/api/5.0/getbuildinfo.do?app_id=2580187")
        
        scan_status=$(echo "$response" | jq -r '.build_info.build[0].analysis_unit[0].status')
        
        if [ "$scan_status" = "Incomplete" ]; then
          echo "Deleting incomplete scan..."
          build_id=$(echo "$response" | jq -r '.build_info.build[0].build_id')
          curl -X DELETE \
            -u "${{ secrets.VERACODE_API_ID }}:${{ secrets.VERACODE_API_KEY }}" \
            "https://analysiscenter.veracode.com/api/5.0/deletebuild.do?build_id=$build_id"
        else
          echo "No incomplete scans found"
        fi

    - name: Veracode Upload And Scan
      uses: veracode/veracode-uploadandscan-action@0.2.6
      with:
        appname: "verademo-net2"
        version: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
        vid: ${{ secrets.VERACODE_API_ID }}
        vkey: ${{ secrets.VERACODE_API_KEY }}
        filepath: ./veracode-upload
        createprofile: true
        deleteincompletescan: true
        debug: true
