name: .NET CI/CD with Veracode Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build with publish
      run: |
        # Buscar el primer archivo .csproj en el repositorio
        csproj_file=$(find . -name "*.csproj" -print -quit)
        if [ -z "$csproj_file" ]; then
          echo "::error::No .csproj file found"
          exit 1
        fi
        
        # Crear directorio para los binarios
        mkdir -p veracode-upload
        
        # Publicar la aplicación
        dotnet publish "$csproj_file" -c Release -o ./veracode-upload --no-self-contained
        
        # Verificar los archivos generados
        echo "Archivos generados:"
        ls -R ./veracode-upload

    - name: Veracode Upload And Scan
      uses: veracode/veracode-uploadandscan-action@0.2.6
      with:
        appname: "verademo-net3"
        version: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
        vid: ${{ secrets.VERACODE_API_ID }}
        vkey: ${{ secrets.VERACODE_API_KEY }}
        filepath: ./veracode-upload
        createprofile: true
        debug: true
